#!/bin/fish
# vim: ft=sh

function proxyctl
    function set_proxy 
        [ "$IS_PROXY_ON" = "1" ] && return 0
        unset_proxy
        set -Ux http_proxy $argv[1]
        set -Ux HTTP_PROXY $http_proxy
        set -Ux https_proxy $http_proxy
        set -Ux HTTPS_PROXY $http_proxy
        set -Ux ftp_proxy $http_proxy
        set -Ux FTP_PROXY $http_proxy
        set -Ux rsync_proxy $http_proxy
        set -Ux RSYNC_PROXY $http_proxy
        set -Ux all_proxy $http_proxy
        set -Ux no_proxy "localhost,127.0.0.1,localaddress,.localdomain.com"
        set -Ux IS_PROXY_ON 1
    end

    function unset_proxy
        set -e http_proxy
        set -e HTTP_PROXY 
        set -e https_proxy 
        set -e HTTPS_PROXY
        set -e ftp_proxy 
        set -e FTP_PROXY
        set -e rsync_proxy
        set -e RSYNC_PROXY 
        set -e all_proxy
        set -e IS_PROXY_ON
        set -e no_proxy 
        set -eg http_proxy
        set -eg HTTP_PROXY 
        set -eg https_proxy 
        set -eg HTTPS_PROXY
        set -eg ftp_proxy 
        set -eg FTP_PROXY
        set -eg rsync_proxy
        set -eg RSYNC_PROXY 
        set -eg all_proxy
        set -eg IS_PROXY_ON
        set -eg no_proxy 
        set -Ux IS_PROXY_ON 0
    end

    function auto_proxy
        set configFile $XDG_CONFIG_HOME/proxy
        set configFileHead (/bin/cat $configFile | head -1)
        set connectedWifi (nmcli -t -f NAME connection show --active)
        set ssid (echo "$configFileHead" | cut -d' ' -f1)
        set proxyServer (echo "$configFileHead" | head -1 | cut -d' ' -f2)

        if [ "$connectedWifi" = "$ssid" ]
            set_proxy "$proxyServer"
        else
            unset_proxy
        end
    end

    function proxy_status
        env | /bin/grep -i "proxy"
    end

    function reset_proxy
        set -e http_proxy
        set -e HTTP_PROXY 
        set -e https_proxy 
        set -e HTTPS_PROXY
        set -e ftp_proxy 
        set -e FTP_PROXY
        set -e rsync_proxy
        set -e RSYNC_PROXY 
        set -e all_proxy
        set -e IS_PROXY_ON
        set -e no_proxy 
        set -eg http_proxy
        set -eg HTTP_PROXY 
        set -eg https_proxy 
        set -eg HTTPS_PROXY
        set -eg ftp_proxy 
        set -eg FTP_PROXY
        set -eg rsync_proxy
        set -eg RSYNC_PROXY 
        set -eg all_proxy
        set -eg IS_PROXY_ON
        set -eg no_proxy 
        auto_proxy
    end 
        
    switch $argv[1]
        case "--set"
            set_proxy
        case "--unset"
            unset_proxy
        case "--status"
            proxy_status
        case "--auto"
            auto_proxy
        case "--reset"
            reset_proxy
        case '*'
            exit 0
    end
end

proxyctl --auto
